# Generated by Django 6.0.5 on 2026-05-16 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('identifiant_suivi', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('structure', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('zone_geographique', models.CharField(blank=True, max_length=255)),
                ('soumission_modifiable_jusqu_au', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Correspondant',
                'verbose_name_plural': 'Correspondants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('libelle', models.CharField(max_length=255)),
                ('descriptif', models.TextField()),
                ('objectifs_pedagogiques', models.TextField()),
                ('duree', models.CharField(max_length=100)),
                ('public_cible', models.TextField()),
                ('nombre_places', models.PositiveIntegerField(default=20)),
                ('periode_previsionnelle', models.CharField(blank=True, max_length=255)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('confirme', models.BooleanField(default=False)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('correspondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='app.correspondant')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
            },
        ),
        migrations.CreateModel(
            name='LienSecurise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('restriction_domaine', models.CharField(blank=True, help_text='Ex : @entreprise.com', max_length=255)),
                ('mot_de_passe', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
                ('formations', models.ManyToManyField(blank=True, related_name='liens', to='app.formation')),
            ],
            options={
                'verbose_name': 'Lien sécurisé',
                'verbose_name_plural': 'Liens sécurisés',
            },
        ),
        migrations.AddField(
            model_name='correspondant',
            name='lien',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondants', to='app.liensecurise'),
        ),
        migrations.CreateModel(
            name='SessionPresentielle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('formateur', models.CharField(max_length=255)),
                ('capacite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.formation')),
                ('participants', models.ManyToManyField(related_name='sessions', through='app.Convocation', to='app.correspondant')),
            ],
            options={
                'verbose_name': 'Session présentielle',
                'verbose_name_plural': 'Sessions présentiel',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='convocation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='app.sessionpresentielle'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('motivations', models.TextField()),
                ('probleme_professionnel', models.TextField(blank=True)),
                ('competences_attendues', models.TextField(blank=True)),
                ('contraintes_calendrier', models.TextField(blank=True)),
                ('contrainte_mobilite', models.BooleanField(default=False)),
                ('format_prefere', models.CharField(blank=True, help_text='Ex : présentiel, distanciel, hybride', max_length=100)),
                ('observation', models.TextField(blank=True)),
                ('correspondant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='app.correspondant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='app.formation')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
                'unique_together': {('correspondant', 'formation')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='convocation',
            unique_together={('session', 'correspondant')},
        ),
    ]
