# Generated by Django 6.0.5 on 2026-05-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sessionpresentielle_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('structure', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('zone_geographique', models.CharField(blank=True, max_length=255)),
                ('motivations', models.TextField()),
                ('probleme_professionnel', models.TextField(blank=True)),
                ('competences_attendues', models.TextField(blank=True)),
                ('contraintes_calendrier', models.CharField(blank=True, max_length=255)),
                ('contrainte_mobilite', models.BooleanField(default=False)),
                ('format_prefere', models.CharField(blank=True, max_length=50)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='app.sessionpresentielle')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
            },
        ),
    ]
