# Generated by Django 6.0 on 2026-05-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
