# Generated by Django 6.0 on 2026-05-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formation_archive_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpresentielle',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sessionpresentielle',
            name='duree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sessionpresentielle',
            name='periode_previsionnelle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sessionpresentielle',
            name='public_cible',
            field=models.TextField(blank=True),
        ),
    ]
