# Generated by Django 6.0 on 2026-05-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_session_champs_supplementaires'),
    ]

    operations = [
        # Clear unique_together FIRST so SQLite can recreate tables without constraint errors
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together=None,
        ),
        # Remove M2M (drops junction table)
        migrations.RemoveField(
            model_name='sessionpresentielle',
            name='participants',
        ),
        # Delete Convocation before its referenced models
        migrations.DeleteModel(
            name='Convocation',
        ),
        # Delete Inscription (removes its FK to Correspondant with it)
        migrations.RemoveField(
            model_name='inscription',
            name='correspondant',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='formation',
        ),
        migrations.DeleteModel(
            name='Inscription',
        ),
        # Remove Correspondant's FK to LienSecurise, then delete
        migrations.RemoveField(
            model_name='correspondant',
            name='lien',
        ),
        migrations.DeleteModel(
            name='Correspondant',
        ),
        # Remove unused fields from LienSecurise
        migrations.RemoveField(
            model_name='liensecurise',
            name='mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='liensecurise',
            name='restriction_domaine',
        ),
    ]
