# Generated by Django 6.0 on 2026-06-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supprimer_correspondant_inscription_convocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='app.formation')),
            ],
            options={
                'verbose_name': 'Thème',
                'verbose_name_plural': 'Thèmes',
                'ordering': ['libelle'],
            },
        ),
        migrations.AddField(
            model_name='avis',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='avis', to='app.theme'),
        ),
    ]
