# Generated by Django 6.0 on 2026-06-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vozaviform_question_vozaviresponse_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionpresentielle',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='liensecurise',
            name='formations',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='sessionpresentielle',
            name='lien',
        ),
        migrations.DeleteModel(
            name='Avis',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='LienSecurise',
        ),
        migrations.DeleteModel(
            name='SessionPresentielle',
        ),
    ]
