# Generated by Django 6.0 on 2026-06-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_vozaviform_user_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozaviform',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('rating', 'Note'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Cases à cocher'), ('text', 'Texte libre'), ('grid', 'Grille de critères'), ('contact', 'Infos personnelles')], max_length=20),
        ),
    ]
