# Generated by Django 6.0 on 2026-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_vozaviform_description_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vozaviform',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Fermé')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='vozaviresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['form', 'position'], name='app_questio_form_id_6477df_idx'),
        ),
    ]
