# Generated by Django 5.2.15 on 2026-06-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vozaviform',
            name='notify_responses',
            field=models.BooleanField(default=True),
        ),
    ]
