# Generated by Django 5.2.15 on 2026-06-22 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_vozaviform_notify_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('user_signup', 'Inscription'), ('user_login', 'Connexion'), ('user_logout', 'Déconnexion'), ('account_deleted', 'Compte supprimé'), ('guest_form_claimed', 'Formulaire invité réclamé'), ('form_created', 'Formulaire créé'), ('form_published', 'Formulaire publié'), ('form_closed', 'Formulaire fermé'), ('form_reopened', 'Formulaire rouvert'), ('form_duplicated', 'Formulaire dupliqué'), ('form_deleted', 'Formulaire supprimé'), ('response_received', 'Réponse reçue'), ('contact_message', 'Message de contact'), ('email_sent', 'E-mail envoyé'), ('email_failed', 'E-mail échoué'), ('account_deactivated', 'Compte désactivé (admin)'), ('account_deleted_by_admin', 'Compte supprimé (admin)')], db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='app_activit_event_t_4cb58c_idx'), models.Index(fields=['actor', 'created_at'], name='app_activit_actor_i_9b5826_idx')],
            },
        ),
    ]
