# Generated by Django 5.2.15 on 2026-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_activityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('user_signup', 'Inscription'), ('user_login', 'Connexion'), ('user_logout', 'Déconnexion'), ('account_deleted', 'Compte supprimé'), ('guest_form_claimed', 'Formulaire invité réclamé'), ('form_created', 'Formulaire créé'), ('form_published', 'Formulaire publié'), ('form_closed', 'Formulaire fermé'), ('form_reopened', 'Formulaire rouvert'), ('form_duplicated', 'Formulaire dupliqué'), ('form_deleted', 'Formulaire supprimé'), ('response_received', 'Réponse reçue'), ('contact_message', 'Message de contact'), ('email_sent', 'E-mail envoyé'), ('email_failed', 'E-mail échoué'), ('account_deactivated', 'Compte désactivé (admin)'), ('account_reactivated', 'Compte réactivé (admin)'), ('account_deleted_by_admin', 'Compte supprimé (admin)')], db_index=True, max_length=40),
        ),
    ]
