# Generated by Django 6.0 on 2026-07-02 12:57

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.FileField(blank=True, storage=app.models.private_storage, upload_to='responses/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('rating', 'Note'), ('single_choice', 'Choix unique'), ('multiple_choice', 'Cases à cocher'), ('text', 'Texte libre'), ('grid', 'Grille de critères'), ('contact', 'Infos personnelles'), ('file', 'Fichier')], max_length=20),
        ),
    ]
